language: cpp

compiler:
  - clang
  - gcc

before_script:
  - sudo apt-get install --assume-yes libhdf5-serial-dev libboost-python-dev libjpeg-dev libtiff4-dev libpng12-dev libfftw3-dev cmake
  - sudo pip install nose
  - sudo pip install numpy
  - sudo pip install cpp-coveralls
   
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DDEPENDENCY_SEARCH_PREFIX=$VIRTUAL_ENV -DAUTOBUILD_TESTS=1 -DAUTOEXEC_TESTS=0 -DWITH_COVERAGE=1 -DVIGRANUMPY_LIBRARIES="/usr/lib/libpython2.7.so;/usr/lib/libboost_python.so" ..
  - make
  - make test

after_success:
  - coveralls -b build
